'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import { AuthGuard } from '@/components/auth/AuthGuard';
import { createPlayable, createSeason, deleteCatalogTitle, deletePlayable, getCatalogTitle, getPlayables, getSeasons, getVideos, setPlayablePublication } from '@/lib/api';
import { CatalogTitle, Playable, Season, Video } from '@/types/video';
import { ChevronRight, Copy, ExternalLink, Film, Plus, RotateCcw, Trash2, Tv } from 'lucide-react';

export default function CatalogDetailPage() { return <AuthGuard><CatalogDetail /></AuthGuard>; }

function CatalogDetail() {
  const params = useParams(); const id = typeof params.id === 'string' ? params.id : '';
  const [title, setTitle] = useState<CatalogTitle | null>(null); const [seasons, setSeasons] = useState<Season[]>([]); const [playables, setPlayables] = useState<Playable[]>([]); const [assets, setAssets] = useState<Video[]>([]); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null);
  const refresh = () => Promise.all([getCatalogTitle(id), getSeasons(id), getPlayables(id), getVideos(1, 100)]).then(([item, seasonList, playableList, library]) => { setTitle(item); setSeasons(seasonList); setPlayables(playableList); setAssets(library.videos.filter((video) => video.status === 'ready')); });
  useEffect(() => { if (id) void refresh().catch((err) => setError(err.message)); }, [id]);
  const movie = useMemo(() => playables.find((item) => item.type === 'movie'), [playables]);
  async function addSeason(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy('season'); try { await createSeason(id, { seasonNumber: Number(form.get('seasonNumber')), title: String(form.get('title') || '') }); await refresh(); event.currentTarget.reset(); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } finally { setBusy(null); } }
  async function addEpisode(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy('episode'); try { await createPlayable(id, { type: 'episode', seasonId: String(form.get('seasonId')), videoId: String(form.get('videoId')), episodeNumber: Number(form.get('episodeNumber')), title: String(form.get('title') || ''), synopsis: String(form.get('synopsis') || ''), artworkUrl: String(form.get('artworkUrl') || '') }); await refresh(); event.currentTarget.reset(); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } finally { setBusy(null); } }
  async function publish(item: Playable, action: 'publish' | 'unpublish' | 'rotate') { setBusy(item.id); try { await setPlayablePublication(item.id, action !== 'unpublish', action === 'rotate'); await refresh(); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } finally { setBusy(null); } }
  async function removePlayable(item: Playable) { if (!window.confirm(`Remove “${item.title}” from this catalog? The uploaded video will remain in your library.`)) return; setBusy(item.id); try { await deletePlayable(item.id); await refresh(); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } finally { setBusy(null); } }
  async function removeTitle() { if (!window.confirm(`Delete “${title?.title}” and all catalog entries? Uploaded videos will remain in your library.`)) return; setBusy('title'); try { await deleteCatalogTitle(id); window.location.href = '/catalog'; } catch (err) { setError(err instanceof Error ? err.message : String(err)); } finally { setBusy(null); } }
  function copyShare(shareId?: string) { if (!shareId) return; void navigator.clipboard.writeText(`${window.location.origin}/embed/${shareId}`); }
  if (!title) return <div className="py-20 text-center text-sm text-muted-foreground">Loading studio record…</div>;
  return <div className="space-y-8"><Link href="/catalog" className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground">Studio <ChevronRight className="h-4 w-4" /> {title.title}</Link>{error && <p className="rounded-lg border border-red-500/40 bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}<section className="rounded-2xl border border-border bg-card p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-accent">{title.type === 'series' ? <Tv className="h-4 w-4" /> : <Film className="h-4 w-4" />}{title.type}</div><h1 className="mt-3 text-3xl font-bold tracking-tight">{title.title}</h1><p className="mt-3 max-w-3xl text-sm text-muted-foreground">{title.synopsis || 'Add a synopsis to make this release easier to recognize.'}</p></div><div className="flex items-center gap-3"><span className={title.status === 'published' ? 'rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-semibold text-emerald-400' : 'rounded-full bg-muted px-3 py-1 text-xs font-semibold text-muted-foreground'}>{title.status}</span><button onClick={removeTitle} disabled={busy === 'title'} className="rounded-md p-2 text-red-300 hover:bg-red-500/10" aria-label="Delete catalog title"><Trash2 className="h-4 w-4" /></button></div></div></section>
  {title.type === 'movie' ? <MoviePanel item={movie} busy={busy} onAction={publish} onRemove={removePlayable} onCopy={copyShare} /> : <><section className="grid gap-5 lg:grid-cols-[260px_1fr]"><form onSubmit={addSeason} className="rounded-xl border border-border bg-card p-5"><h2 className="font-semibold">Add season</h2><p className="mt-1 text-xs text-muted-foreground">The rail establishes the playback order.</p><input required min="1" type="number" name="seasonNumber" placeholder="Season number" className="mt-4 w-full rounded-md border border-border bg-background px-3 py-2 text-sm" /><input name="title" placeholder="Season title (optional)" className="mt-2 w-full rounded-md border border-border bg-background px-3 py-2 text-sm" /><button disabled={busy === 'season'} className="mt-3 inline-flex items-center gap-2 rounded-md bg-accent px-3 py-2 text-sm font-semibold text-accent-foreground"><Plus className="h-4 w-4" /> Add season</button><div className="mt-6 space-y-1">{seasons.map((season) => <div key={season.id} className="border-l-2 border-accent/70 py-2 pl-3 text-sm"><span className="font-semibold">S{season.seasonNumber}</span><span className="ml-2 text-muted-foreground">{season.title || 'Untitled season'}</span></div>)}</div></form><form onSubmit={addEpisode} className="rounded-xl border border-border bg-card p-5"><h2 className="font-semibold">Add episode</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><select required name="seasonId" defaultValue="" className="rounded-md border border-border bg-background px-3 py-2 text-sm"><option value="" disabled>Choose season</option>{seasons.map((season) => <option key={season.id} value={season.id}>Season {season.seasonNumber}</option>)}</select><input required min="1" type="number" name="episodeNumber" placeholder="Episode number" className="rounded-md border border-border bg-background px-3 py-2 text-sm" /><input required name="title" placeholder="Episode title" className="rounded-md border border-border bg-background px-3 py-2 text-sm sm:col-span-2" /><select required name="videoId" defaultValue="" className="rounded-md border border-border bg-background px-3 py-2 text-sm sm:col-span-2"><option value="" disabled>Choose a ready upload</option>{assets.map((asset) => <option key={asset.id} value={asset.id}>{asset.title}</option>)}</select><textarea name="synopsis" placeholder="Episode synopsis" className="min-h-20 rounded-md border border-border bg-background px-3 py-2 text-sm sm:col-span-2" /></div><button disabled={busy === 'episode' || !seasons.length} className="mt-3 inline-flex items-center gap-2 rounded-md bg-accent px-3 py-2 text-sm font-semibold text-accent-foreground disabled:opacity-50"><Plus className="h-4 w-4" /> Add episode</button></form></section><EpisodeRail seasons={seasons} playables={playables} busy={busy} onAction={publish} onRemove={removePlayable} onCopy={copyShare} /></>}</div>;
}

function MoviePanel({ item, busy, onAction, onRemove, onCopy }: { item?: Playable; busy: string | null; onAction: (item: Playable, action: 'publish' | 'unpublish' | 'rotate') => Promise<void>; onRemove: (item: Playable) => Promise<void>; onCopy: (shareId?: string) => void }) { if (!item) return <div className="rounded-xl border border-dashed border-border p-8 text-sm text-muted-foreground">This movie does not have a linked video asset.</div>; return <PlayableActions item={item} busy={busy} onAction={onAction} onRemove={onRemove} onCopy={onCopy} />; }
function EpisodeRail({ seasons, playables, busy, onAction, onRemove, onCopy }: { seasons: Season[]; playables: Playable[]; busy: string | null; onAction: (item: Playable, action: 'publish' | 'unpublish' | 'rotate') => Promise<void>; onRemove: (item: Playable) => Promise<void>; onCopy: (shareId?: string) => void }) { return <section className="space-y-5">{seasons.map((season) => <div key={season.id} className="rounded-xl border border-border bg-card"><div className="border-b border-border px-5 py-4"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-accent">Season {season.seasonNumber}</p><h2 className="mt-1 font-semibold">{season.title || 'Episodes'}</h2></div><div className="divide-y divide-border">{playables.filter((item) => item.seasonId === season.id).map((item) => <div key={item.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold text-muted-foreground">E{item.episodeNumber}</p><p className="font-medium">{item.title}</p><p className="mt-1 text-sm text-muted-foreground">{item.synopsis || 'No synopsis.'}</p></div><PlayableActions item={item} busy={busy} onAction={onAction} onRemove={onRemove} onCopy={onCopy} compact /></div>)}{!playables.some((item) => item.seasonId === season.id) && <p className="px-5 py-6 text-sm text-muted-foreground">No episodes in this season.</p>}</div></div>)}</section> }
function PlayableActions({ item, busy, onAction, onRemove, onCopy, compact = false }: { item: Playable; busy: string | null; onAction: (item: Playable, action: 'publish' | 'unpublish' | 'rotate') => Promise<void>; onRemove: (item: Playable) => Promise<void>; onCopy: (shareId?: string) => void; compact?: boolean }) { return <div className={`flex flex-wrap items-center gap-2 ${compact ? '' : 'mt-5 rounded-xl border border-border bg-card p-5'}`}><span className={item.status === 'published' ? 'text-xs font-semibold text-emerald-400' : 'text-xs font-semibold text-muted-foreground'}>{item.status}</span>{item.status === 'published' ? <><button onClick={() => onCopy(item.shareId)} className="inline-flex items-center gap-1 rounded-md border border-border px-2 py-1.5 text-xs hover:bg-muted"><Copy className="h-3.5 w-3.5" /> Copy link</button><a href={item.shareId ? `/embed/${item.shareId}` : '#'} target="_blank" className="inline-flex items-center gap-1 rounded-md border border-border px-2 py-1.5 text-xs hover:bg-muted"><ExternalLink className="h-3.5 w-3.5" /> Preview</a><button disabled={busy === item.id} onClick={() => onAction(item, 'rotate')} className="rounded-md px-2 py-1.5 text-xs text-muted-foreground hover:bg-muted"><RotateCcw className="inline h-3.5 w-3.5" /> Rotate</button><button disabled={busy === item.id} onClick={() => onAction(item, 'unpublish')} className="rounded-md px-2 py-1.5 text-xs text-red-300 hover:bg-red-500/10">Unpublish</button></> : <button disabled={busy === item.id} onClick={() => onAction(item, 'publish')} className="rounded-md bg-accent px-3 py-1.5 text-xs font-semibold text-accent-foreground">Publish & create link</button>}<button disabled={busy === item.id} onClick={() => onRemove(item)} className="rounded-md p-1.5 text-red-300 hover:bg-red-500/10" aria-label="Remove from catalog"><Trash2 className="h-3.5 w-3.5" /></button></div> }
