version: 2

updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    groups:
      frontend-production:
        dependency-type: production
        patterns:
          - "*"
      frontend-development:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: gomod
    directories:
      - /infra/nginx/cache-purger
      - /infra/nginx/cache-purger/testorigin
      - /services/analytics
      - /services/auth
      - /services/cdn-origin
      - /services/gateway
      - /services/internal
      - /services/metadata
      - /services/upload
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /services/transcoder
    schedule:
      interval: weekly
      day: tuesday
      time: "05:45"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    groups:
      transcoder-python:
        patterns:
          - "*"

  - package-ecosystem: docker
    directories:
      - /frontend
      - /infra/nginx
      - /infra/nginx/cache-purger
      - /infra/nginx/cache-purger/testorigin
      - /services/analytics
      - /services/auth
      - /services/cdn-origin
      - /services/gateway
      - /services/metadata
      - /services/transcoder
      - /services/upload
    schedule:
      interval: weekly
      day: tuesday
      time: "06:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    groups:
      docker-images:
        patterns:
          - "*"

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: "06:15"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    groups:
      compose-images:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: "06:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
